#!/usr/bin/env bash
# displays information about the Best School file.

FILE="Best School"

if [ -e "$FILE" ]
then
    echo "Best School file exists"
    if [ ! -s "$FILE" ]
    then
        echo "Best School file is empty"
    else
        echo "Best School file is not empty"
    fi
    if [ -f "$FILE" ]
    then
        echo "Best School is a regular file"
    fi
else
    echo "Best School file does not exist"
fi
